- type: job
  id: SecurityCadet
  name: job-name-cadet
  description: job-description-cadet
  playTimeTracker: JobSecurityCadet
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 14400 # DeltaV - 4 hours
    - !type:CharacterDepartmentTimeRequirement # Ronstation - Readds time limit
      department: Security
      min: 54000 #15 hrs
      inverted: true # stop playing intern if you're good at security!
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Blindness
        - Pacifist
        - BrittleBoneDisease
  startingGear: SecurityCadetGear
  icon: "JobIconSecurityCadet"
  supervisors: job-supervisors-security
  canBeAntag: false
  access:
  - Security
  #- Brig # Delta V: Removed
  - Maintenance
  - Service
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 6
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellHigh

- type: startingGear
  id: SecurityCadetGear
  subGear:
  - SecurityOfficerPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorRed
    back: ClothingBackpackSecurity
    shoes: ClothingShoesBootsCombatFilled
    outerClothing: ClothingOuterArmorDuraVest # DeltaV - ClothingOuterArmorBasic replaced in favour of stab vest. Sucks to suck, cadets
    id: SecurityCadetPDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
    pocket2: BookSecurity
  innerClothingSkirt: ClothingUniformJumpskirtColorRed
  satchel: ClothingBackpackSatchelSecurity
  duffelbag: ClothingBackpackDuffelSecurity
