- type: department
  id: Logistics # DeltaV - Logistics Department replacing Cargo
  description: department-Cargo-description
  color: "#A46106"
  roles:
  - CargoTechnician
  - Quartermaster
  - SalvageSpecialist
  - MailCarrier # Nyanotrasen - MailCarrier, see Resources/Prototypes/Nyanotrasen/Roles/Jobs/Cargo/mail-carrier.yml

- type: department
  id: Civilian
  description: department-Civilian-description
  color: "#9FED58"
  weight: -10
  roles:
  - Bartender
  - Botanist
  - Boxer
  - Chaplain # Ronstation - Move Chaplain into Service
  - Chef
  - Clown
  - HeadOfPersonnel
  - Janitor
  # - Lawyer # DeltaV - Move Lawyer into Justice
  - Mime
  - Musician
  - Passenger
  - Reporter
  - Visitor
  - Zookeeper
  - ServiceWorker
  - MartialArtist # Nyanotrasen - MartialArtist, see Resources/Prototypes/Nyanotrasen/Roles/Jobs/Wildcards/martialartist.yml
  - Prisoner # Nyanotrasen - Prisoner, see Resources/Prototypes/Nyanotrasen/Roles/Jobs/Wildcards/prisoner.yml
  - Gladiator # Nyanotrasen - Gladiator, see Resources/Prototypes/Nyanotrasen/Roles/Jobs/Wildcards/gladiator.yml
  - Librarian # Ronstation - Move Librarian into Service

- type: department
  id: Command
  description: department-Command-description
  color: "#334E6D"
  roles:
  - Captain
  - CentralCommandOfficial
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfPersonnel
  - HeadOfSecurity
  - ResearchDirector
  - Quartermaster
  - ChiefJustice # DeltaV - chief justice is in command staff
  - CentralCommandOfficial
  - CBURN
  - ERTLeader
  - ERTChaplain
  - ERTJanitor
  - ERTMedical
  - ERTSecurity
  - ERTEngineer
  - DeathSquad
  - AdministrativeAssistant # Delta V - Administrative Assistant, see Resources/Prototypes/Nyanotrasen/Roles/Jobs/Command/admin_assistant.yml
  primary: false
  weight: 100

- type: department
  id: Dignitary
  description: department-Dignitary-description
  color: "#33FE6D"
  roles:
  - BlueshieldOfficer # Goobstation
  - NanotrasenRepresentative # Goobstation
  - Magistrate # Goobstation
  primary: false
  weight: 101

- type: department
  id: Engineering
  description: department-Engineering-description
  color: "#EFB341"
  roles:
  - AtmosphericTechnician
  - ChiefEngineer
  - SeniorEngineer
  - StationEngineer
  - TechnicalAssistant

- type: department
  id: Medical
  description: department-Medical-description
  color: "#52B4E9"
  roles:
  - Chemist
  - ChiefMedicalOfficer
  - MedicalDoctor
  - MedicalIntern
  - Psychologist
  - Paramedic
  - SeniorPhysician
  - MedicalBorg  # Delta V - Medical Borg, see Resources/Prototypes/DeltaV/Roles/Jobs/Medical/medicalborg.yml

- type: department
  id: Security
  description: department-Security-description
  color: "#DE3A3A"
  weight: 20
  roles:
  - HeadOfSecurity
  - SecurityCadet
  - SecurityOfficer
  - SeniorOfficer
  - Detective
  - Warden
  - PrisonGuard # Nyanotrasen - PrisonGuard, see Resources/Prototypes/Nyanotrasen/Roles/Jobs/Security/prisonguard.yml
  - Brigmedic # DeltaV - Brigmedic, see Resources/Prototypes/DeltaV/Roles/Jobs/Security/brigmedic.yml

- type: department
  id: Epistemics # Ronstation - Science Department replacing Epistemics. Science roles moved to Ronstation's departments.yml.
  description: department-Science-description
  color: "#D381C9"
  roles:
   - ResearchDirector # Ronstation - Science Department replacing Epistemics.
   - SeniorResearcher # Ronstation - Science Department replacing Epistemics.
   - Scientist # Ronstation - Science Department replacing Epistemics.
   - ResearchAssistant # Ronstation - Science Department replacing Epistemics.
  # - Chaplain # Ronstation - Role rework.
   - ForensicMantis # Nyanotrasen - ForensicMantis, see Resources/Prototypes/Nyanotrasen/Roles/Jobs/Epistemics/forensicmantis.yml
  # - Librarian # Ronstation - Librarian is now in Service
   - Roboticist # Ronstation - Science Department replacing Epistemics.
  primary: false

- type: department
  id: Silicon
  description: department-Silicon-description
  color: "#D381C9"
  roles:
  - Borg
  - StationAi

- type: department
  id: Specific
  description: department-Specific-description
  color: "#9FED58"
  weight: 10
  roles:
  - Boxer
  - Reporter
  - Zookeeper
  - Psychologist
  - MartialArtist # Nyanotrasen - MartialArtist, see Resources/Prototypes/Nyanotrasen/Roles/Jobs/Wildcards/martialartist.yml
  - Gladiator # Nyanotrasen - Gladiator, see Resources/Prototypes/Nyanotrasen/Roles/Jobs/Wildcards/gladiator.yml
  - Prisoner # Nyanotrasen - Prisoner, see Resrouces/Prototypes/Nyanotrasen/Roles/Jobs/Wildcards/prisoner.yml
  - Brigmedic # DeltaV - Corpsman, see Resources/Prototypes/DeltaV/Roles/Jobs/Security/brigmedic.yml
  - ForensicMantis # Ronstation - Mantis is only available on specific maps.
  primary: false
