- type: job
  id: ForensicMantis
  name: job-name-mantis
  description: job-description-mantis
  playTimeTracker: JobForensicMantis
  setPreference: true
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 18000
    - !type:CharacterDepartmentTimeRequirement
      department: Epistemics # DeltaV - Epistemics Department replacing Science
      min: 3600
    - !type:CharacterLogicOrRequirement
      requirements:
  #      - !type:CharacterSpeciesRequirement
  #        inverted: true
  #        species:
  #          - IPC
  #      - !type:CharacterTraitRequirement
  #        traits:
  #          - AnomalousPositronics
        - !type:CharacterTraitRequirement
          inverted: true
          traits:
            - Pacifist
  #      - !type:CharacterTraitRequirement
  #        inverted: true
  #        traits:
  #          - ShadowkinBlackeye
  startingGear: ForensicMantisGear
  icon: "JobIconForensicMantis"
  supervisors: job-supervisors-rd
  antagAdvantage: 5 # DeltaV - From 4 to 5
  canBeAntag: false # Ronstation - Mantis is now a "warden" of science.
  # whitelistRequired: true
  access:
  - Research
  - Maintenance
  - Mantis # DeltaV - Mantis, see Resources/Prototypes/DeltaV/Access/epistemics.yml
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ] # Ronstation - Mantis is science's warden.
  #- !type:AddComponentSpecial
  #  components:
  #  - type: Psionic
  #    powerSlots: 2
  #- !type:AddComponentSpecial
  #  components:
  #  - type: InnatePsionicPowers
  #    powersToAdd:
  #      - MetapsionicPower
  #      - TelepathyPower
  #      - AssayPower

- type: startingGear
  id: ForensicMantisGear
  subGear:
  - ForensicMantisPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMantis
    back: ClothingBackpackMantisFilled
    shoes: ClothingShoesBootsMantis
    head: ClothingHeadHatFezMantis
    id: ForensicMantisPDA
    eyes: ClothingEyesGlassesSunglasses
    ears: ClothingHeadsetScience
    gloves: ClothingHandsGlovesColorWhite
    outerClothing: ClothingOuterCoatMantis
    belt: ClothingBeltMantis
    pocket1: BookPsionicsGuidebook
  innerClothingSkirt: ClothingUniformSkirtMantis
  satchel: ClothingBackpackSatchelMantisFilled
  duffelbag: ClothingBackpackDuffelMantisFilled

- type: startingGear
  id: ForensicMantisPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitMantis
    head: ClothingHeadEnvirohelmMantis
    gloves: ClothingHandsGlovesEnviroglovesWhite
